spring:
  application:
    name: order-platform

  datasource:
    url: jdbc:postgresql://localhost:5433/order_platform_db
    username: order_user
    password: order_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    # --- Configuração de Retry + Backoff Exponencial ---
    listener:
      simple:
        retry:
          enabled: true           # Ativa a tentativa automática de reprocessamento
          max-attempts: 3         # Quantidade máxima de tentativas (1 original + 2 retries)
          initial-interval: 1000ms # 1ª espera: 1 segundo
          multiplier: 2.0         # Fator de multiplicação (1s -> 2s)
          max-interval: 10000ms   # Teto máximo de espera entre tentativas

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

server:
  port: 8080
