name: Order Platform CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ develop, staging, main, master ]
  pull_request:
    branches: [ develop, staging, main, master ]

jobs:
  code-quality:
    name: Build, Test & Quality Gate (SonarQube)
    runs-on: self-hosted

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compilar, Executar Testes e Enviar para o SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn clean test org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=order-platform-api \
            -Dsonar.projectName="Order Platform API" \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.token=$SONAR_TOKEN \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

  deploy-dev:
    name: Deploy - Ambiente DEV
    needs: code-quality
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    runs-on: self-hosted
    environment: development
    steps:
      - name: Deploy Container DEV (Porta 8081)
        run: |
          APP_PORT=8081 SPRING_PROFILES_ACTIVE=dev CONTAINER_NAME=order-platform-dev \
          docker compose -p order-platform-dev up -d --build

  deploy-test:
    name: Deploy - Ambiente TEST
    needs: code-quality
    if: github.ref == 'refs/heads/staging' && github.event_name == 'push'
    runs-on: self-hosted
    environment: testing
    steps:
      - name: Deploy Container TEST (Porta 8082)
        run: |
          APP_PORT=8082 SPRING_PROFILES_ACTIVE=test CONTAINER_NAME=order-platform-test \
          docker compose -p order-platform-test up -d --build

  deploy-prod:
    name: Deploy - Ambiente PROD
    needs: code-quality
    if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') && github.event_name == 'push'
    runs-on: self-hosted
    environment: production
    steps:
      - name: Deploy Container PROD (Porta 8080)
        run: |
          APP_PORT=8080 SPRING_PROFILES_ACTIVE=prod CONTAINER_NAME=order-platform-prod \
          docker compose -p order-platform-prod up -d --build
